project:
  type: book
  output-dir: _book

book:
  title: "Drawing Inferences"
  author: "Marius Furter"
  date: today
  sidebar:
    logo: images/drawing-inferences-logo.png
    tools: []
  navbar:
    background: none
    title: " "
    search: true
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: [cosmo, theme/custom-light.scss]
      dark:  [darkly, theme/custom-dark.scss]
    code-fold: true
    toc: true
    number-sections: true
    math: true

execute:
  freeze: auto
