::: {.hidden}
$$
 \def\then{\mathbin{;}}
 \def\kernel{\rightsquigarrow}
 \def\swap{\mathsf{swap}}
 \def\id{\mathsf{id}}
 \def\cp{\mathsf{copy}}
 \def\del{\mathsf{del}}
 \def\supp{\mathsf{supp}}
 \def\ivmark#1{[\![#1]\!]}
$$
:::

# Conditioning and Intervening

Conditioning and intervening are update operations on models. Both can be expressed by intuitive graphical manipulations of string diagrams.

Conditioning: New generative process once certain outputs have been observed.

Intervening: New generative process once certain outputs have been forced to take specific values. Only makes sense if model structure has causal content, ie we expect that exchanging one mechanism for another will be faithfully reflected in reality.

## Conditioning

[The following is all about conditioning on points. Should we also discuss conditioning on general events?]

::: {#def-conditioned-kernel}

Let $g : X \otimes Y \kernel U \otimes W$ be a discrete kernel. 

**Pre-conditioning on input:** $g_{\mid X=\bar x} : Y \kernel U \otimes W$ to be $g$ with fixed value $\bar x$:
$$
g_{\mid X=\bar x}(u,w \mid y) := g(u,w \mid \bar x, y).
$$

**Pre-conditioning on output:** $g_{\mid U=\bar u} : X \otimes Y \kernel W$ to be $g$ with fixed value $\bar u$:
$$
g_{\mid U=\bar u}(w \mid x,y) := g(\bar u,w \mid x,y).
$$

More generally, we define $g_{\mid U} : X \otimes Y \kernel W$ to be the kernel that takes $u$ as an input and outputs $g_{\mid U=u}$:
$$
g_{\mid U}(w \mid x,y) := g(u,w \mid x,y).
$$


Pre-conditioning on inputs preserves normalization. Pre-conditioning on outputs does not preserve normalization.
:::

Given a string diagram, we can condition on an observation $U = \bar u$ as follows:

1. Delete all wires that carry $U$.
2. Replace any boxes $g$ that take $U$ as input or output by their pre-conditioned versions $g_{\mid U=\bar u}$.
3. Normalize the resulting diagram.

This procedure is justified by applying the definition of conditional distribution to the sum-product expression for the diagram.

To condition on several variables, repeat the procedure for each variable. The order of conditioning does not matter.

It is also possible to view the conditioned model as taking $U = \bar u$ as a new input. In this case, we perform the same steps as above, but a afterwards feed $U$ as in input to all preconditioned boxes.

### Conditional independence

::: {#def-conditional-independence}

Graphical definition of conditional independence.

:::

Consider a string diagram of probability kernels [does this hold more generally? where is this assumption used?]. To check if $U$ and $W$ are conditionally independent given $X$ do the following:

1. Delete all outputs except $U$ and $W$.
2. Reduce to normal form (by applying delete axioms)
3. Delete all wires that carry $X$. (equivalently, pre-condition on $X$)
4. Check if $U$ and $W$ are disconnected in the resulting diagram.

[Does order of 2 and 3 matter?]

This procedure works for general string diagrams, as shown by @FritzDSeparation2023.

### Sampling from non-normalized kernels

Let $g : X \kernel Y$ be a discrete kernel. As long as there are no $x \in X$ with $g(- \mid x) = 0$, we can write 
$$g(y \mid x) = w(x) \, g'(y \mid x)$$

where $w(x) := \sum_{y \in Y} g(y \mid x)$ and $g'(y \mid x) = \frac{g(y \mi x)}{w(x)}$ is a probability kernel. Kernels that can be written in this way are said to have full support. In string diagrams, this corresponds to writing

[Diagram]

We call boxes of the form $w : X \kernel I$ **weights**.

Using this representation to evaluate a test function $t : Y \to I$, we observe that
$$
    (g \then t)(\bullet \mid x) = \sum_{y \in Y} t(y) \, g(y \mid x) =  \sum_{y \in Y} w(x) t(y) \, g'(y \mid x).
$$

By the Law of Large numbers, we can approximate $(g \then t)$ by sampling $y_i \sim g'(- \mid x)$ and computing the weighted average 
$$
    (g \then t)(\bullet \mid x) \approx \frac{1}{n} \sum_{i=1}^n w(x_i) t(y_i).
$$

Hence, sampling from $g$ can be realized by drawing **weighted samples** $(y_i, w(x_i))$ where $y_i \sim g'(-\mid x_i)$ and computing weighted averages.

More generally, suppose we are given a string diagram consisting of probability kernels $f_i$ and weights $w_j$. For example, such diagrams arise from pre-conditioning. One can also convert a diagram of general kernels to this form as long as they have full support.

When evaluating a test function $t$, we can move all the weights to the right and view them as being composed in parallel with the test function. Hence the result is equivalent to evaluating $\left( \prod_j w_j \right) \, t$ against the diagram containing only the $f_i$. 

[Diagram illustrating this idea.]

This justifies the following weighted sampling procedure:

Follow the wires of the diagram from left to right:
1. For each probability kernel $f_i : X_i \kernel Y_i$, given input $x_i$, sample $y_i \sim f_i( - \mid x_i)$.
2. For each weight $w_j : X_j \kernel I$, record $w_j(x_j)$.

After all boxes have been traversed:
1. Multiply all accumulated weights $w = \prod_j w_j(x_j)$.
2. Return weighted sample $([y_1, \ldots, y_n] w)$.

Given $N$ weighted samples ([y_1^k, \ldots, y_n^k] w^k), evaluate a test function $t$ by $\frac{1}{N} \sum_k w^k t(y_1^k, \ldots, y_n^k)$.

Compare to rejection sampling: 
For $g : X \kernel Y \otimes Z$, write 
$$g_{\mid Z = \bar z}(y \mid x) = g(y, \bar z \mid x) = \sum_{z} \ivmark{z = \bar z} g(y,z \mid x)$$

[Diagram comparing the two factorizations.]

Hence, we can also sample from the pre-conditioned kernel by drawing samples from $g$ and weighting all samples not satisfying $z = \bar z$ with zero. Computing weighted averages
$$
    g_{\mid Z = \bar z} \then t = \frac{1}{N} \sum_{i=1}^N \ivmark{z_i = \bar z} t(y_i) = \frac{1}{N} \sum_{i : z_i = \bar z} t(y_i).
$$

shows that this procedure is equivalent to rejecting samples that do not satisfy the condition $Z = \bar z$.

## Intervening

General intervention of box $f$: Replace $f$ with $f'$. Interventions preserve normalization if $f$ and $f'$ are normalized kernels.

Usually, we consider two special types of interventions:

- **Do** intervention: Replace $f : X \kernel Y$ with $\del_X \then \delta_{\bar y}$, where $\delta_{\bar y}$ is the kernel that outputs $\bar y$ with probability 1.

- **Soft** intervention: Replace $f : X \kernel Y$ with $\del_X \then m$, where $m : I \kernel Y$ is a probability distribution over $Y$.

Both of these delete the input wires of $f$ and fix $Y$ to a specific value (do) or distribution (soft).

